### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Thieum** [madskristensen/Madskristensen.VisualStudio.SDK#10]
As far as I understand, this package has been replaced by https://www.nuget.org/packages/Microsoft.VisualStudio.SDK/ -  It would be helpful if this NuGet package was marked as deprecated on nuget.org and pointing to the newer version of it.

**Comment by madskristensen** [comment]
It's not deprecated as such, since it's the only one of the two NuGet packages that supports VSSDK 14.0

**Comment by Thieum** [comment]
@madskristensen ah I see! I still felt it was better to upgrade to the MS one considering my targets, but I can see how it could convey the wrong message for other consumers of this package, Thanks for the clarification!
