### ISSUE TITLE
Add Microsoft.VisualStudio.CommandBars v8.0.0.0

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/Madskristensen.VisualStudio.SDK#3]
Currently blocked by VS Extensibility team who need to upload it to NuGet first

**Comment by mrlacey** [comment]
Looks like this can be closed as now added https://github.com/madskristensen/Madskristensen.VisualStudio.SDK/commit/42b392db6a104080fe9e48956b117015f9728816
