### ISSUE TITLE
Microsoft.VisualStudio.Debugger.Metadata.15.8.28010 fails to install for 15.6.78 to 15.8.80 packages

### ISSUE THREAD

**Issue by Thieum** [madskristensen/Madskristensen.VisualStudio.SDK#4]
Steps to reproduce:
1. Create a new VSIX project
2. Check that target framework is 4.6
3. try to install Madskristensen.VisualStudio.SDK 15.8.80-pre
4. The install will fail on the package Microsoft.VisualStudio.Debugger.Metadata
```
Successfully installed 'Microsoft.VisualStudio.Debugger.Interop.15.0 15.8.28010' to VSIXProject2
Install failed. Rolling back...
Package 'Microsoft.VisualStudio.Debugger.Metadata.15.8.28010' does not exist in project 'VSIXProject2'
```
The latest package in the 15.X family that works is 15.3.80-pre, all the other version from there fail with the same error.

Visual Studio used:

Using Visual Studio 2017 15.9.3

**Comment by madskristensen** [comment]
I just saw this today as well. I know how to fix it and an update is coming later today

**Comment by madskristensen** [comment]
Fixed with commit https://github.com/madskristensen/Madskristensen.VisualStudio.SDK/commit/a2c6ff94a664a5be7eaa6888ade08c74d9bc0432

**Comment by madskristensen** [comment]
Grab the latest meta package from NuGet where it should have been fixed
